spring:
  application:
    name: tingeso-entrega1
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/tingeso1
    username: postgres
    password: 1234
  sql:
    init:
      mode: always
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8091

